# Generated by Django 2.2 on 2019-04-29 10:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=None, null=True)),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('name', models.CharField(choices=[('WN', 'Weekly News'), ('MD', 'Closest Deadlines')], default='MD', max_length=2, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
