# Generated by Django 2.2 on 2019-04-29 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mailinglist', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('id', 'created')},
        ),
    ]
